{% set name = "ilamb" %}
{% set version = "2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://bitbucket.org/ncollier/ilamb
  git_rev: v{{ version }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - netcdf4
  run:
    - python
    - numpy
    - scipy
    - netcdf4
    - sympy
    - mpi4py
    - cfunits
    - matplotlib
    - basemap

about:
  home: https://csdms.colorado.edu/wiki/Model:ILAMB
  license:
  summary:
    The International Land Model Benchmarking (ILAMB) project is a
    model-data intercomparison and integration project designed to
    improve the performance of land models and, in parallel, improve
    the design of new measurement campaigns to reduce uncertainties
    associated with key land surface processes.
  dev_url: https://bitbucket.org/ncollier/ilamb
