language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/conda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "wZhT7d63wQi6G/TwgOOdF26PXZaTU/6E+WdJz1zVlkF6h3xhESgUYvZisbUsTeL2a22llLbupTJ+krHwyg28tAs3LodcP3LVLZw8xWl25kSqc7K2nxafUQlt0sxLlUx0CEGlBgLPbDYyjkjWYV7+/bkT6tVoba/ZZzCQb+/MQCMLHDvAMpVVuJmV2ZYaZR/C287QyEGQRJJgXHYYm2el5pX8M0ecWTO3oZevSb9tK1mktOavr1COKshUq6IALZ8g4lgsjlokhqQ9bUxlSE6/bd3lrjoPy6yQiYdbf4W1u7d4X9Jytjf1/BvM3BpdKWHHcBCtF1mKXvOxQhVrdBWS4KzZfsJyIIvBzwWQxvVtzydw1+5+Ifzb6sf1vY8vQsJZz6isnloSKlMK/aN7DAT3EQa/dNWDrb6NAexdBRMCBA/4ecR5PzaApfjMSpDhdAEd09FfiO+JZpNekwL3SOvG1diylbP4TMOfUkA/AeluG8ssKiUn4302yjDASziOyYFlNYYJNSGQ+qWVKgRpvVMDMdwPCnqtn6Wx1KlDKQegs4mRejryrU/xwmLDoLJADhGbwlvF71eQeDF/KLgbE/0iFHJZ9spnYwv9RlzyVSLOnVcFsdHeLt20TO58Ivpcwmhs66QqoLuwgDvePyCaRP6Pblzmm1KrsXW0S0ZrMt3kcgY="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c defaults -c conda-forge --old-build-string
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-

