#!/usr/bin/env bash

# PLEASE NOTE: This script has been automatically generated by
# conda-smithy. Any changes here will be lost next time ``conda smithy
# rerender`` is run. If you would like to make permanent changes to
# this script, consider a proposal to conda-smithy so that other
# feedstocks can also benefit from the improvement.

FEEDSTOCK_ROOT=$(cd "$(dirname "$0")/.."; pwd;)
RECIPE_ROOT=$FEEDSTOCK_ROOT/recipe

docker info

config=$(cat <<CONDARC

channels:
 - csdms-stack
 - defaults # As we need conda-build
 - conda-forge

conda-build:
 root-dir: /feedstock_root/build_artefacts

show_channel_urls: true

CONDARC
)

cat << EOF | docker run -i \
                        -v ${RECIPE_ROOT}:/recipe_root \
                        -v ${FEEDSTOCK_ROOT}:/feedstock_root \
                        -a stdin -a stdout -a stderr \
                        mcflugen/centos \
                        bash || exit $?

export BINSTAR_TOKEN=${BINSTAR_TOKEN}
export PYTHONUNBUFFERED=1
export PATH=/usr/local/miniconda/bin:$PATH

echo "$config" > ~/.condarc
# A lock sometimes occurs with incomplete builds. The lock file is stored in build_artefacts.
conda clean --lock

conda config --set always_yes yes --set changeps1 no
conda install python=2.7
conda install -q 'conda-build>=3'
conda install -q anaconda-client coverage sphinx

conda build /recipe_root --quiet || exit 1

curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > anaconda_upload.py
echo $BINSTAR_TOKEN | python anaconda_upload.py /recipe_root --channel=main --org=csdms-stack --token=-
EOF
